version: "3"
services:
  admin-service:
    # 指定容器名称
    container_name: admin-web
    # 重启机制
    restart: always
    image: java:8
    volumes:
      # 本地jar包路径
      - /usr/gourd/gourd-hu/admin-web.jar:/admin-web.jar
      # 挂载日志 -v A:B ,A指宿主机位置，B指容器位置
      - ./logs:/logs
      # 指定容器时间为宿主机时间
      - /etc/localtime:/etc/localtime
    # 访问端口
    ports:
      - "10001:10001"
    environment:
      # 指定时区
      - TZ="Asia/Shanghai"
    #启动容器后执行的命令
    entrypoint: java -server -Xms256m -Xmx256m -jar -Dspring.profiles.active=local -Dspring.cloud.nacos.discovery.ip=xxxxx admin-web.jar