version: '3'
services:
  openapi-service:
    image: tomcat:9.0.33
    ports:
      - "8088:8080"
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xmx256m -Xms256m
    entrypoint:
      - "catalina.sh"
      - "run"
    volumes:
      - ./tomcat-web/webapps:/usr/local/tomcat/webapps
      # 挂载日志 -v A:B ,A指宿主机位置，B指容器位置
      - ./tomcat-web/logs:/usr/local/tomcat/logs
      # 指定容器时间为宿主机时间
      - /etc/localtime:/etc/localtime
    container_name: openapi